version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build --tag=sbrunner/scan-to-paperless .
      - run: docker build --tag=tests tests
      - run: docker run --rm tests pylint process
      - run: docker run --rm tests python3 -m pyflakes .
      - run: docker run --rm tests bandit -r process
      - run: docker run --rm tests mypy --ignore-missing-imports --disallow-untyped-defs --strict-optional --follow-imports skip /opt
      - run: docker run --rm tests codespell --check-filenames --skip=./Deskew/*,*.pyc,*.png
      - run: docker run --rm --env=PYTHONPATH=/opt/ --volume=`pwd`/results:/results tests bash -c 'mv /opt/process /opt/process.py; cd /tests; pytest --verbose --color=yes .'
      - store_artifacts:
          path: results
          destination: tests-results
