---
version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          update_type: all
          dependency_type: all
    allowed_updates:
      - match:
          dependency_type: all
